# Load dependencies
library(rstan)
library(lubridate)
library(ggthemes)
library(reshape2)
library(assertthat)
library(tidyverse)
library(mgcv)
library(ggridges)
library(patchwork)
library(scales)
library(ggrepel)
theme_set(theme_minimal())
source('R/helpers.R')
